### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [sheepduke/chameleon#2]
Building with SBCL 2.1.11.140-4dd1b0aaa / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id ddb303af5d52b996c897f40a72dc448579e41d16

*chameleon/tests* fails to build with the following error:

```
Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1042230283}>: The name "CHAMELEON-TESTS.CONFIG" does not designate any package.

```

[Full log here](http://report.quicklisp.org/2022-01-08/failure-report/chameleon.html)

**Comment by sheepduke** [comment]
It is due to a bug in ASDF file. Fixed in `2.1.1`. Closing.
